apiVersion: apps/v1
kind: Deployment
metadata:
  name: ipfs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ipfs
  template:
    metadata:
      labels:
        app: ipfs
    spec:
      nodeSelector:
        'beta.kubernetes.io/os': linux
      containers:
        - name: ipfs
          image: ipfs/go-ipfs:latest
          env:
            - name: IPFS_SWARM_KEY_FILE
              value: /mnt/ipfsconfig/swarm.key
            - name: IPFS_PATH
              value: /mnt/ipfsdata
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          volumeMounts:
            - name: ipfsconfig
              mountPath: /mnt/ipfsconfig
            - name: ipfsdata
              mountPath: /mnt/ipfsdata
          ports:
            - containerPort: 4001
              name: ipfs-web2
      volumes:
        - name: ipfsconfig
          persistentVolumeClaim:
            claimName: azurefile
        - name: ipfsdata
          azureDisk:
            kind: Managed
            diskName: ctaks
            diskURI: default
