---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-internal
spec:
  type: NodePort
  ports:
    - port: 5001
      name: ipfs-int-web
    - port: 4001
      name: ipfs-int-core
  selector:
    app: ipfs
